# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-alpine

# Set working directory
WORKDIR /app

# Install dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev
RUN pip install --no-cache-dir alpha-vantage httpx mcp[cli]

# Copy source code
COPY . .

# Expose no port for stdio

CMD ["python", "main.py"]
